export type { CacheTag } from "@/lib/cache/tags";
export {
  cacheTags,
  brandDetailTag,
  companyDetailTag,
  contactDetailTag,
  eventDetailTag,
  orgActionTemplatesListTag,
  orgActionsListTag,
  orgBrandsListTag,
  orgCompaniesListTag,
  orgContactsListTag,
  orgDashboardTag,
  orgEventsListTag,
  orgNotesListTag,
  orgParticipationsListTag,
  orgProfilesListTag,
  orgSmmListTag,
  participationDetailTag,
  profileTag,
} from "@/lib/cache/tags";
